name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths:
      - "CPU/**"
      - "GPU/**"
  pull_request:
    branches: [ main ]
    paths:
      - "CPU/**"
      - "GPU/**"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file CPU/20.04/ROS1/base.Dockerfile --tag robolaunch:ros-base
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
        
    - name: Build and push
      id: docker_build1
      uses: docker/build-push-action@v2
      with:
        context: ./
          
        # Dockerfile to use for building
        file: ./CPU/20.04/ROS1/base.Dockerfile
        push: true
          
        # Image name.
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/noetic:base
          
        # Cache build layer so you can make use of previously built layers
        cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/noetic:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/noetic:buildcache,mode=max
        
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file CPU/20.04/ROS2/base.Dockerfile --tag robolaunch:ros-base
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Set up Docker Buildx
      id: buildx1
      uses: docker/setup-buildx-action@v1
        
    - name: Build and push
      id: docker_build11
      uses: docker/build-push-action@v2
      with:
        context: ./
          
        # Dockerfile to use for building
        file: ./CPU/20.04/ROS2/base.Dockerfile
        push: true
          
        # Image name.
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/foxy:base
          
        # Cache build layer so you can make use of previously built layers
        cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/foxy:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/foxy:buildcache,mode=max
        
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file CPU/20.04/bridge.Dockerfile --tag robolaunch:ros-base
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Set up Docker Buildx
      id: buildx2
      uses: docker/setup-buildx-action@v1
        
    - name: Build and push
      id: docker_build2
      uses: docker/build-push-action@v2
      with:
        context: ./
          
        # Dockerfile to use for building
        file: ./CPU/20.04/bridge.Dockerfile
        push: true
          
        # Image name.
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/noetic-foxy:base
          
        # Cache build layer so you can make use of previously built layers
        cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/noetic-foxy:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/noetic-foxy:buildcache,mode=max


    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file CPU/20.04/fcaps.Dockerfile --tag robolaunch:ros-base
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Set up Docker Buildx
      id: buildx3
      uses: docker/setup-buildx-action@v1
        
    - name: Build and push
      id: docker_build3
      uses: docker/build-push-action@v2
      with:
        context: ./
          
        # Dockerfile to use for building
        file: ./CPU/20.04/fcaps.Dockerfile
        push: true
          
        # Image name.
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/noetic-foxy:fcaps
          
        # Cache build layer so you can make use of previously built layers
        cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/noetic-foxy-fcaps:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/noetic-foxy-fcaps:buildcache,mode=max
